openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de Dominios
  description: Documentaci贸n de la API de Dominios de la materia 75.43 Introducci贸n a Sistemas Distribuidos, TP1. Grupo BEROCH, NITZ, GIORDANO.

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicaci贸n
paths:
  /domains/{domain}:
    get:
      operationId: "api.dominios.obtener_uno"
      tags:
        - "Dominios"
      summary: "Obtener IP"
      description: "Obtiene la IP asociada a un dominio en particular"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El dominio para el cual quiero obtener su IP.
      responses:
        '200':
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/domain'
        '404':
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /custom-domains:
    post:
      operationId: "api.dominios.crear"
      tags:
        - "Dominios"
      summary: "Nuevo Dominio Custom"
      description: "Crea una entrada para sobreescribir la IP de un dominio en particular"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inputCustomDomain'
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/domain'
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    get:
      operationId: "api.dominios.buscar_custom"
      tags:
        - "Dominios"
      summary: "Buscar dominios custom existentes"
      description: "Buscar en la base de datos todos los dominios custom que contengan la query en su nombre"
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: false
          description: "Mostrar solo los custom domain que tengan esta query en su nombre."
      responses:
        '200':
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customDomainList'  


  /custom-domains/{domain}:
    put:
      operationId: "api.dominios.actualizar"
      tags:
        - "Dominios"
      summary: "Actualizar Dominio"
      description: "Edita un dominio ya existente en el sistema."
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El dominio que quiero editar.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inputCustomDomain'
      responses:
        '200':
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/domain'

    delete:
      operationId: "api.dominios.borrar"
      tags:
        - "Dominios"
      summary: "Borar Dominio"
      description: "Borra un dominio existente en el sistema."
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El dominio que quiero borrar.
      responses:
        '200':
          description: "Ok"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  domain: 
                    type: "string"
        '404':
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

# Declaraci贸n de tipos de datos
components:
  schemas:
    domain:
      type: object
      properties:
        domain:
          type: string
        ip:
          type: string
        custom:
          type: boolean
    error:
      type: object
      properties:
        error: 
          type: string
    inputCustomDomain:
      type: object
      properties:
        domain:
          type: string
        ip:
          type: string
    customDomainList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/domain'

