openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de Dominios
  description: Documentaci贸n de la API de Dominios de la materia 75.43 Introducci贸n a Sistemas Distribuidos, TP1. Grupo BEROCH, NITZ, GIORDANO.

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicaci贸n
paths:
  /domains/{domain}:
    get:
      operationId: "api.dominios.obtener_uno"
      tags:
        - "Dominios"
      summary: "Dominio"
      description: "Obtiene la IP asociada a un dominio en particular"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El domain para el cual quiero obtener su IP.
      responses:
        200:
          description: "IP obtenida exitosamente"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/domain'

# Declaraci贸n de tipos de datos
components:
  schemas:
    domain:
      type: "object"
      properties:
        domain:
          type: "string"
        ips:
          type: "array"
        lastAccesedIP:
          type: "integer"
        custom:
          type: "boolean"
